package com.upbest.persistence;

import java.util.List;

import com.upbest.model.SysInfo;

public interface SysInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbggenerated Wed Dec 10 13:04:43 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbggenerated Wed Dec 10 13:04:43 CST 2014
     */
    int insert(SysInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbggenerated Wed Dec 10 13:04:43 CST 2014
     */
    int insertSelective(SysInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbggenerated Wed Dec 10 13:04:43 CST 2014
     */
    SysInfo selectByPrimaryKey(Integer id);

    
    SysInfo findInfoByFactoryCode(String code);
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbggenerated Wed Dec 10 13:04:43 CST 2014
     */
    int updateByPrimaryKeySelective(SysInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbggenerated Wed Dec 10 13:04:43 CST 2014
     */
    int updateByPrimaryKey(SysInfo record);
    
    
    List<SysInfo>  findAllInfo();
}