package com.upbest.model;

import java.util.Date;

public class SysLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.id
     *
     * @mbggenerated Fri Dec 12 14:27:13 CST 2014
     */
    private Integer id;
    private Integer stationId;
    
    
    
    public Integer getStationId() {
		return stationId;
	}

	public void setStationId(Integer stationId) {
		this.stationId = stationId;
	}
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.user_id
     *
     * @mbggenerated Fri Dec 12 14:27:13 CST 2014
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.create_time
     *
     * @mbggenerated Fri Dec 12 14:27:13 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.class_name
     *
     * @mbggenerated Fri Dec 12 14:27:13 CST 2014
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.method_name
     *
     * @mbggenerated Fri Dec 12 14:27:13 CST 2014
     */
    private String methodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.log_desc
     *
     * @mbggenerated Fri Dec 12 14:27:13 CST 2014
     */
    private String logDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.id
     *
     * @return the value of sys_log.id
     *
     * @mbggenerated Fri Dec 12 14:27:13 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.id
     *
     * @param id the value for sys_log.id
     *
     * @mbggenerated Fri Dec 12 14:27:13 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.user_id
     *
     * @return the value of sys_log.user_id
     *
     * @mbggenerated Fri Dec 12 14:27:13 CST 2014
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.user_id
     *
     * @param userId the value for sys_log.user_id
     *
     * @mbggenerated Fri Dec 12 14:27:13 CST 2014
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.create_time
     *
     * @return the value of sys_log.create_time
     *
     * @mbggenerated Fri Dec 12 14:27:13 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.create_time
     *
     * @param createTime the value for sys_log.create_time
     *
     * @mbggenerated Fri Dec 12 14:27:13 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.class_name
     *
     * @return the value of sys_log.class_name
     *
     * @mbggenerated Fri Dec 12 14:27:13 CST 2014
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.class_name
     *
     * @param className the value for sys_log.class_name
     *
     * @mbggenerated Fri Dec 12 14:27:13 CST 2014
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.method_name
     *
     * @return the value of sys_log.method_name
     *
     * @mbggenerated Fri Dec 12 14:27:13 CST 2014
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.method_name
     *
     * @param methodName the value for sys_log.method_name
     *
     * @mbggenerated Fri Dec 12 14:27:13 CST 2014
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.log_desc
     *
     * @return the value of sys_log.log_desc
     *
     * @mbggenerated Fri Dec 12 14:27:13 CST 2014
     */
    public String getLogDesc() {
        return logDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.log_desc
     *
     * @param logDesc the value for sys_log.log_desc
     *
     * @mbggenerated Fri Dec 12 14:27:13 CST 2014
     */
    public void setLogDesc(String logDesc) {
        this.logDesc = logDesc == null ? null : logDesc.trim();
    }
}